example/consumer.js
example/producer.js
src/index.js
src/producer.js
src/registry.js
src/runner.js
src/task.js
test/producer.js
test/runner.js
test/task.js
types/index.js

initial stab at a central event emitter
----
----
----
----

initial stab at a central event emitter

---

src/runner.js

log topic and message when a task fails

---

src/task.js
test/task.js

add ability to pass in a single message, rather than array
----
----
----
----

add ability to pass in a single message, rather than array

---

src/runner.js

Move runner event receive prior to running, also add new complete event.
----
----
----
----

Move runner event receive prior to running,

---

.flowconfig
.gitignore
.travis.yml
flow-typed/npm/lazy-object.js
flow-typed/npm/moment.js
flow-typed/npm/no-kafka.js
package.json
src/admin.js
src/config.js
src/index.js
src/producer.js
src/runner.js
types/index.js
yarn.lock

Flow type coverage

---

package.json
src/producer.js
test/producer.js

Log size of JSON stringified payload. Is this good enough?

log payload size

---

package.json
src/admin.js

Minor changes to get consumer lag

Consumer lag

---

package.json
src/producer/kafka.js
src/producer/redis.js
src/producer/sqs.js
yarn.lock

Use momentjs to get the Unix timestamp.

Bring moment

---

README.md
package.json
src/base/base_runner.js
src/config/redis.js
src/config/sqs.js
src/runner/kafka.js
src/runner/redis.js
src/runner/sqs.js
types/index.js
yarn.lock

Add filter option for selective processing

Filter topics

---

example/producer.js
package.json
src/base/base_runner.js
src/runner/sqs.js

- Fix SQS queue creation 
- If queue already exisits, SQS gives the existing queue information

fix sqs createqueue

---

src/runner/redis.js
src/runner/sqs.js
test/runner/sqs.js

modify process to process in a series

---

example/consumer.js
example/producer.js
package.json
src/base/base_runner.js
src/producer/redis.js
src/producer/sqs.js
src/registry.js
src/runner/redis.js
src/runner/sqs.js
types/index.js
yarn.lock

intersection, not difference - add argument to bind

---

example/consumer.js
example/producer.js
package.json
src/base/pool.js
src/base/runner.js
src/config.js
src/index.js
src/runner/kafka.js
src/runner/redis.js
src/runner/sqs.js
test/runner/redis.js
test/runner/sqs.js
types/index.js
yarn.lock

new worker pool implementation

---

src/base/base_runner.js
src/runner/sqs.js

This branch implements a fix to pass in the queue configuration parameters when creating queues
----
----
----

Pass in config to create queues

---

package.json
src/base/base_runner.js
src/base/runner.js
src/index.js
src/runner/kafka.js
src/runner/redis.js
src/runner/sqs.js
test/base/base_runner.js
test/mocha.opts
types/index.js

Add concept of hooks to steveo to allow process to check the environment health and terminate if required

Healthchecks and termination locks

---

package.json
src/config/sqs.js
types/index.js
yarn.lock

Production Release

---

example/consumer.js
src/base/base_runner.ts
src/common.ts
src/config/sqs.ts
src/producer/sqs.ts
src/runner/sqs.ts
test/producer/sqs_test.ts
test/runner/sqs_test.ts

Add concurrency limits on sqs runner.
This just uses bluebird to prevent overloading the consumer

Add concurrency limits on sqs runner

---

src/runner/sqs.ts

correctly parse concurrency

---

src/index.ts

add context to type def in task method

add context to type def in task method

---

package.json
src/base/base_runner.ts
src/common.ts
src/producer/sqs.ts

Add HealthCheck to Runner

---

package.json
src/runner/sqs.ts

Includes the original message in the below log line to make debugging certain errors easier
----
As above
----
Install steveo@5.1.0-beta2 and pass a bad SQS message to a task for processing
----
----

include original message on SQS error log

---

package.json
src/producer/sqs.ts
src/runner/sqs.ts

Fix to ensure tasks are within concurrency limits.
----
- Adds missing `await` statements
----
----
----

Fix for SQS task lifecycle

---

.github/workflows/release.yml

https://github.com/changesets/action/issues/311

need to add an extra token variable for publishing

---

.changeset/hungry-horses-remain.md
packages/newrelic/CHANGELOG.md
packages/newrelic/package.json
packages/scheduler-prisma/CHANGELOG.md
packages/scheduler-prisma/package.json
packages/scheduler-sequelize/CHANGELOG.md
packages/scheduler-sequelize/package.json
packages/sentry/CHANGELOG.md
packages/sentry/package.json
packages/statsd/CHANGELOG.md
packages/statsd/package.json
packages/steveo/CHANGELOG.md
packages/steveo/package.json

Want to trigger the publish action

update version using changeset

---

apps/sequelize-example/src/steveo_sqs.ts

Fix reference to logger

---

.changeset/heavy-walls-beam.md
packages/datadog/.eslintignore
packages/datadog/.gitignore
packages/datadog/.mocharc.yml
packages/datadog/README.md
packages/datadog/package.json
packages/datadog/src/index.ts
packages/datadog/test/.eslintrc
packages/datadog/test/index_test.ts
packages/datadog/tsconfig.json
yarn.lock

Wraps publish and consume events with a datadog trace. If the data dog collector is not set up then this becomes a no-op and should not cause a failure.

Add a datadog trace middleware

---

.github/workflows/main.yml
apps/prisma-example/package.json
apps/sequelize-example/package.json
packages/scheduler-prisma/package.json
packages/scheduler-sequelize/package.json

> **Changes**
- Added missing package scope
- edited workflow yml file
- and bump eslint-config-ordermentum

fix: added missing om package scope and updated workflow file

---

.github/workflows/release.yml

> **Context**
- Builds are failing on release step
> **Changes**
- added npm auth token to release workflow

Added NPM auth token to release workflow

---

packages/scheduler-prisma/test/helpers_test.ts
packages/scheduler-sequelize/test/helpers_test.ts

- Fix skipped and failing rrule test cases

Fix rrule test cases

---

.changeset/spicy-mirrors-bow.md
packages/steveo/src/common.ts
packages/steveo/src/consumers/sqs.ts
packages/steveo/src/producers/sqs.ts
packages/steveo/test/consumer/sqs_test.ts

> **Changes**
- Added FIFO support

[C1-1154] Added fifo support to SQS

---

.changeset/spotty-seahorses-tickle.md
packages/steveo/src/config.ts
packages/steveo/src/lib/manager.ts
packages/steveo/test/integration/sqs_test.ts

Ensure manger waits for runners and producers to shutdown

Platform 1603 make sure steveo manager waits for shutdown

---

.changeset/purple-starfishes-sell.md
packages/steveo/src/common.ts
packages/steveo/src/index.ts
packages/steveo/src/lib/logger.ts
packages/steveo/src/producers/kafka.ts
packages/steveo/src/producers/sqs.ts
packages/steveo/src/runtime/task.ts
packages/steveo/src/runtime/workflow.ts
packages/steveo/test/common/index_test.ts
packages/steveo/test/common/task_test.ts
packages/steveo/test/consumer/kafka_test.ts
packages/steveo/test/consumer/sqs_test.ts
packages/steveo/test/integration/redis_test.ts
packages/steveo/test/producer/kafka_test.ts
packages/steveo/test/producer/sqs_test.ts

Adds generic types on publish methods to support different options per engine

[DevX-143] Add engine message options

---

.changeset/gold-falcons-matter.md
packages/scheduler-prisma/src/index.ts
packages/scheduler-sequelize/src/index.ts

Minor tweak to allow us to see the terminate function actually wait for workers to complete
----
----
----
----

update terminate log output

---

.changeset/yellow-swans-rush.md
packages/steveo/src/consumers/sqs.ts
packages/steveo/src/index.ts

- Added worker configuration details to the Steveo Runner start log.
- Introduced timing for message processing in SQS Runner to log processing duration.
- Updated polling logic to reduce delay when work is done, improving responsiveness.

Enhance SQS Runner logging and processing efficiency
