ordermentum/steveo

src/task.js
test/task.js

accept non-promise callbacks
----
----
----
----

accept non-promise callbacks

---

package.json
src/runner/kafka.ts
src/runner/sqs.ts

Receiving message in the sqs runner is an unguarded promise that can break the loop and stop processing. 
This PR adds a catch on that promise and doesn't let the error bubble up to the main process.

Add error handling when receiving a message from sqs

---

packages/steveo/package.json
packages/steveo/src/consumers/kafka.ts
packages/steveo/test/consumer/kafka_test.ts

Kafka consumers in steveo use a non-flowing mode which means we explicitly tell the consumer to consumer a new message (and we manually commit the message offset).
With the new manager state logic, consumers now look at statuses in their polling/streaming callback. When a kafka consumer is `paused` we break the callback loop by returning and not telling it to consume, so the consumer never restarts, even though the steveo instance's state changes to `running`.
This PR adds a logic to ignore messages if the consumer is supposed to be paused and does not commit. It'll re-read the same message till the steveo instance goes to either `terminating` or `running`

Fix resuming of kafka consumers

---

.changeset/thick-icons-compare.md
packages/steveo/package.json
packages/steveo/src/consumers/kafka.ts
yarn.lock

We are using `getMetadata` api to get us information of the broker we are connected to. By default it fetches the whole object with all topics. 
This PR changes it to fetch minimal info so we check connection. Health check wouldn't care about all topics.
This will fix the broker unknown topic error we are seeing with consumers (verified on my local, to be tested on our pods).

Kafka - Change metadata parameters when checking consumer health

---

.changeset/flat-cherries-exercise.md
packages/cloudwatch/src/index.ts

The cloudwatch client isn't able to pick up the region through environment vars. This PR explicitly sets it.

Cloudwatch metrics emitter - Set AWS region

---

.changeset/lemon-beds-occur.md
packages/scheduler-prisma/package.json
packages/scheduler-prisma/src/definitions/lunartick.d.ts
packages/scheduler-prisma/src/helpers.ts
packages/scheduler-prisma/src/index.ts
packages/scheduler-prisma/test/helpers_test.ts
packages/scheduler-prisma/tsconfig.json
packages/scheduler-sequelize/package.json
packages/scheduler-sequelize/src/helpers.ts
packages/scheduler-sequelize/src/maintenance.ts
packages/scheduler-sequelize/test/helpers_test.ts
yarn.lock

Integrates https://github.com/lsndr/rrule-rust that wraps the [rrule crate](https://crates.io/crates/rrule) that follows the [iCalendar (RFC-5545) specification](https://icalendar.org/iCalendar-RFC-5545/3-3-10-recurrence-rule.html) more accurately than the outdated homegrown https://github.com/ordermentum/lunartick
This is tested locally with sequelize ORM.
A workaround needed to be added for rules containing the `TZID` attribute which is added separately with date starts as listed in the iCal RFC. The workaround is to remove the attribute and use the job's timezone field.

[C1-971] Replace lunartick with rust rrule

---

packages/scheduler-prisma/test/helpers_test.ts
packages/scheduler-sequelize/package.json
packages/scheduler-sequelize/test/recurrence_generators_test.ts
yarn.lock

The following limitations to using lunartick for ical rules were discovered:
1. It does not support interval with rules that are monthly and have an interval > 1 (e.g. `FREQ=MONTHLY;BYMONTHDAY=17;INTERVAL=2`)
2. It does not support fortnightly rules (e.g. `FREQ=WEEKLY;BYDAY=TH;INTERVAL=2`)
3. It does not support `BYMONTHDAY=-1` (https://github.com/ordermentum/lunartick/blob/develop/src/iterator.js#L110 shifts the date by an extra month)
4. It does not support multiple values for BYDAY (e.g. `FREQ=WEEKLY;BYDAY=MO,WE,FR`)
5. It does not support `BYSETPOS` parameter (e.g. `FREQ=DAILY;BYHOUR=8,18;BYMINUTE=30,0;BYSETPOS=1,4`)
6. It does not chronologically sort BY rules (e.g. Values will be different for `FREQ=DAILY;BYHOUR=8,18;BYMINUTE=0,30` and `FREQ=DAILY;BYHOUR=8,18;BYMINUTE=30,0` - Note …

Add tests for recurrence generators

---

.github/workflows/main.yml
.github/workflows/release.yml

This PR adds the `workflow_dispatch` attribute to `main` and `release` workflows to allow them to be triggered manually.

Allow workflows to be manually triggered

---

.changeset/afraid-wasps-repair.md
packages/datadog/package.json
packages/steveo/src/producers/kafka.ts
packages/steveo/test/producer/kafka_test.ts

Adds a check to see if the kafka producer is connected before disconnecting. This prevents an error being thrown for an unconnected producer getting a disconnect call.

Cleanup-producer-disconnect

---

.changeset/famous-brooms-hunt.md
packages/scheduler-prisma/README.md
packages/scheduler-prisma/src/helpers.ts
packages/scheduler-prisma/test/helpers_test.ts
packages/scheduler-sequelize/README.md
packages/scheduler-sequelize/src/helpers.ts
packages/scheduler-sequelize/src/maintenance.ts
packages/scheduler-sequelize/test/helpers_test.ts
packages/scheduler-sequelize/test/recurrence_generators_test.ts

https://ordermentum.atlassian.net/browse/SUPPLIER-2916
- `computeNextRun` that generates a single next run
- `computeNextRuns` that generates n next occurrences. `count` = occurrences that need to be generated, default 1
- Porting of this code to prisma scheduler
- Changeset added
- Initial set of tests

Adds helper method for generating n next occurrences

---

.changeset/spicy-dolphins-impress.md
.gitignore
packages/steveo/src/consumers/sqs.ts
packages/steveo/src/lib/context.ts
packages/steveo/test/consumer/sqs_test.ts

This PR fixes the issues of the context not being passed correctly by the SQS runner to the task handlers, and introduces a new unit test to unsure the context is correctly injected, if present in the message.
This issues was introduced during the migration from Steveo 5 to Steveo 6 when the code that handled the message unpacking was removed, probably due to some name confusion that was mixing the message context and the Steveo runtime context (Responsible for storing runtime info, such as processing startTime and endTime, etc).
----
----
----
----

[DEVOPS] Fix scheduler context unpacking issue

---

.changeset/shiny-turkeys-play.md
packages/steveo/src/consumers/kafka.ts
packages/steveo/test/consumer/kafka_test.ts

> **Context**
- SQS and Redis expose the whole payload within the data/value, however, in kafka it stores it under value field/attribute making it hard to align the type for the expected task callback payload vs publish payload.
> **Changes**
- Store all kafka related informations on a metadata within the parsed data
This will avoid us calling steveo instead of the actual task: https://github.com/ordermentum/xero/compare/C1-1153-steveo-kafka-payload-update?expand=1
ticket: https://ordermentum.atlassian.net/browse/C1-1153

[C1-1153] Modified payload parsing of received message from kafka

---

.changeset/light-gifts-attack.md
packages/scheduler-prisma/src/helpers.ts
packages/scheduler-prisma/src/index.ts
packages/scheduler-prisma/test/helpers_test.ts
packages/scheduler-sequelize/src/helpers.ts
packages/scheduler-sequelize/src/index.ts
packages/scheduler-sequelize/test/helpers_test.ts
packages/steveo/src/common.ts
packages/steveo/src/consumers/kafka.ts
packages/steveo/src/consumers/sqs.ts
packages/steveo/src/lib/context.ts
packages/steveo/src/producers/kafka.ts
packages/steveo/src/producers/sqs.ts
packages/steveo/src/task.ts
packages/steveo/test/consumer/kafka_test.ts
packages/steveo/test/consumer/sqs_test.ts
packages/steveo/test/producer/kafka_test.ts
packages/steveo/test/producer/sqs_test.ts

Currently, when the scheduler picks a job to be executed and verifies whether the task at hand is of type Publishable.
If it is, the scheduler calls the Task::publish method, which accepts a task payload, and a context.
The problem is that the code that calls the `Task::publish` method (`taskRunner` helper), merges the job data and the job metadata, instead of calling `Task::publish(jobData, jobPayload). As a result, Tasks that rely on the context break since the context is now part of the payload.
To fix it, it is required to change the `taskRunner` to avoid merging the 2 objects, which causes a chain of changes in the producers to accept an optional context, and changes in the consumers to unpack the message and extract payload and metadata, before calling the task Callback function. …

Fix scheduler merging context with data

---

.changeset/three-waves-sort.md
packages/scheduler-prisma/src/helpers.ts
packages/scheduler-prisma/test/helpers_test.ts
packages/scheduler-sequelize/src/helpers.ts
packages/scheduler-sequelize/test/helpers_test.ts

- As the PR title says have added a way to support recurrences formatted with DTSTART at the end of the string
----
- Use `startsWith` instead of `includes` to determine if it's an iCal rule
- If it's not an iCal rule but includes a DTSTART, format it in a way that the new library can parse it. That means moving DTSTART at the start of the string and trimming it from the rule

Support recurrences that have DTSTART at the end of the recurrence string

---

.changeset/stale-keys-argue.md
packages/steveo/src/consumers/kafka.ts
packages/steveo/test/consumer/kafka_test.ts

> **Context**
- Previous version v6.4.0 had a breaking change which was augmented by renovate automatic versioning which led integrator to not sync at all. Given this issue, we want to avoid it by making the callback payload backwards compatible
> **Changes**
- Added back `value` property on the kafka callback

[C1-1226] Added value property back into the callback payload

---

.changeset/lazy-rats-lay.md
packages/steveo/src/lib/manager.ts

Found that pods are terminating too early, and need a higher default wait period

Increase the default termination wait count to give the process longer to complete

---

packages/datadog/package.json
packages/datadog/src/global.d.ts
packages/newrelic/package.json
packages/newrelic/src/global.d.ts
packages/scheduler-prisma/src/global.d.ts
packages/scheduler-sequelize/src/global.d.ts
packages/sentry/package.json
packages/sentry/src/global.d.ts
packages/statsd/package.json
packages/statsd/src/global.d.ts
packages/steveo/src/common.ts
packages/steveo/src/producers/sqs.ts
tsconfig.json

* Move steveo to a dev dependency so that turbo builds it first
* use the `*` so that turbo gets the right version of steveo
* put the ReadableStream declaration into the common file because AWS have some weird type issues

Fix import chain

---

.changeset/tricky-squids-bow.md
packages/datadog/src/index.ts
packages/datadog/test/index_test.ts
packages/datadog/tsconfig.json

Updates DatadogMiddleware propagate the DD traces down the message life cycle. [PLATFORM-1544](https://ordermentum.atlassian.net/browse/PLATFORM-1544)
1. During the message publishing the extracts the `trace_id` and `parent_id` from the current context and injects it to the message `_meta` attributes, under the `datadog` key.
2. During the message processing, if the message `_meta` attributes contains a datadog key, then its content is extracted and associated with the current context as a parent.
----
----
----
----
[PLATFORM-1544]: https://ordermentum.atlassian.net/browse/PLATFORM-1544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …

[PLATFORMS-1544] Implement dd-trace in DD middleware

---

.changeset/rotten-chefs-sit.md
apps/workflows-example/package.json
apps/workflows-example/src/config.ts
packages/storage-postgres/package.json

This PR fixes the broken release step due to mismatch in package name.
What changes:
- Rename `@steveojs/store-postgres` to `@steveojs/storerage-postgres` to match package folder name
- Update Change the to fix package name
----
----
----
----

Rename storage-postgres package and fix changeset

---

.changeset/fresh-tips-walk.md
packages/datadog/tsconfig.json

Fix datadog lib folder structure, introduced by latest minor upgrade.
In the 7.1.0 version, the tests folder was added to the includes list, in the `tsconfig.json` which caused the compile `lib` folder to contains new `src` and `test` folders instead of containing only the `index.js` entrypoint file.
Wrong structure:
Correct Structure:
----
----
----
----

[BUGFIX] Remove test folder from tsconfig include list

---

.changeset/tough-dryers-greet.md
packages/steveo/src/common.ts
packages/steveo/src/config.ts
packages/steveo/src/config/sqs.ts
packages/steveo/src/consumers/base.ts
packages/steveo/src/producers/kafka.ts
packages/steveo/src/producers/sqs.ts
packages/steveo/test/integration/sqs_test.ts
packages/steveo/test/producer/sqs_test.ts

The issue occurred due to inconsistencies in local and non-local environments, because locally the AWS credentials env variables are required while in non-local we use the instance role, therefore the credentials are not required.
This PR introduces a new configuration attributes in the SQS config called `credentials`, which is a wrapper around the optional `accessKeyId` and `secretAccessKey`.
The credentials attribute is also optional but the `accessKeyId` and `secretAccessKey` are not mandatory.
**PS: Do not worry about the changes on the consumers and producers.**  Those change only prefixing the engine name to the logs message to improve logs search. Eventually they could be in the log context, but that's a bigger change for the future.
----
---- …

[BUGFIX] AWS SQS connection issues with credentials

---

.changeset/fuzzy-hats-begin.md
.changeset/khaki-mayflies-pump.md
packages/datadog/src/index.ts
packages/datadog/test/index_test.ts
packages/steveo/src/consumers/kafka.ts
packages/steveo/src/producers/kafka.ts
packages/steveo/test/consumer/kafka_test.ts
packages/steveo/test/producer/kafka_test.ts

There is an issue (more like an easter egg) preventing Kafka message from being produced when `DatadogMiddleware` is activated.
The issue happens basically because `DatadogMiddleware` expectes payload to be a dictionary so it can inject the Datadog traces in the message. However, Kafka is sending a Message.value attribute, which is a string causing the following error.
```
Cannot create property '_meta' on string '*' 
```
This PR makes sure that both Kafka producers and Kafra consumers sends the payload to all middlewares as a dictionary, instead of a dictionary.
----
----
----
----

[BUGFIX] Kafka producer failing with DatadogMiddleware

---

.changeset/breezy-chicken-notice.md
packages/datadog/src/index.ts

Datadog middleware sends an incorrect object to the function that extracts Datadog context info from the current span.
This is causing the spans not to connect anymore.
----
----
----
----

Fix datadog context receiving incorrect object

---

.changeset/moody-countries-end.md
packages/steveo/src/consumers/sqs.ts

We currently log _"Message received for task"_ twice per message, which may mislead people into believing they are receiving and/or handling more messages than they actually are.
----
Changes the second log instance to a `debug` log with a different message.
----
----
----

Remove double logging of the same message

---

packages/steveo/src/index.ts
packages/steveo/src/runtime/workflow.ts
packages/steveo/src/types/workflow-repo.ts
packages/steveo/src/types/workflow.ts
packages/steveo/test/workflow/fixtures/repo_fixture.ts
packages/steveo/test/workflow/fixtures/workflow_fixture.ts
packages/steveo/test/workflow/workflow_test.ts
packages/storage-postgres/src/repo/workflow-postgres-repo.ts

Workflows should delete their state from the postgres db upon successful completion.
This PR adds a new option to the workflow (default 'true') to delete completed states. This has been made optional so developers can opt not to delete them during development for debug purposes.

add workflow deletion option on completion

---

.changeset/gold-falcons-hammer.md
packages/steveo/src/common.ts
packages/steveo/src/index.ts
packages/steveo/src/runtime/task.ts

This PR types publish methods on [Task](https://github.com/ordermentum/steveo/blob/main/packages/steveo/src/runtime/task.ts#L15) and the [root Steveo instance](https://github.com/ordermentum/steveo/blob/main/packages/steveo/src/index.ts#L177) to only support object shaped payloads.
[This breaks kafka tasks being able to accept strings](https://github.com/ordermentum/steveo/blob/main/packages/steveo/src/producers/kafka.ts#L85) but it had 2 issues: 
- It didn't support adding tracing info on messages
- Trust boundary was violated. Kafka runner assumed it received valid strings. 
This change will give us better protection when publishing payloads on sqs/kafka tasks.

[Steveo] Type publish methods to enforce payloads to be object shaped

---

.changeset/afraid-toes-mate.md
packages/steveo/src/consumers/kafka.ts
packages/steveo/src/consumers/sqs.ts
packages/steveo/src/lib/context.ts
packages/steveo/test/consumer/kafka_test.ts
packages/steveo/test/consumer/sqs_test.ts

Steveo consumers emit `runner_complete` event with a `duration` in the context argument. 
Duration is meant to be the time elapsed from `producer producing the message -> consumer processing and running the task`
The api used to calculate the diff `process.hrtime` is not synced across node processes. Which means the event duration is not accurate. It's the reason [we see negative values as duration.](https://app.datadoghq.com/logs?query=@topic:PRODUCTION_ORDER-SCHEDULE-PLACEMENT%20@metric_name:runner_success_ms&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=service,@kubernetes.pod_name&event=AwAAAZSwF2VlTBCMUwAAABhBWlN3RjJWbEFBQXdaaGI0eFZNWC1nSkcAAAAkMDE5NGIwMTctNjU2NS00YjQyLTk2ZTMtYTE4NTQ5OWQxZjM2AAAFZw&fromUser=true&index=metrics&messageDisplay=expan …

[DevX-173] [Steveo] Fix runtime duration calculation

---

packages/steveo/src/lib/context.ts
packages/steveo/test/consumer/kafka_test.ts
packages/steveo/test/consumer/sqs_test.ts

Companion change to https://github.com/ordermentum/steveo/pull/863
Adding a new field to not break service to service processing.
`process.hrtime` throws an exception if a wrong argument is passed
```sh
> process.hrtime(12321312)
Uncaught:
TypeError [ERR_INVALID_ARG_TYPE]: The "time" argument must be an instance of Array. Received type number (12321312)
at process.hrtime (node:internal/process/per_thread:74:5) {
code: 'ERR_INVALID_ARG_TYPE'
}
```

[DevX-173] [Steveo] Make duration calculation backwards compatible

---

.changeset/ten-buses-appear.md
apps/tasks-example/package.json
apps/workflows-example/package.json
packages/steveo/package.json
packages/steveo/src/config.ts
packages/steveo/src/consumers/kafka.ts
packages/steveo/test/common/config_test.ts
packages/storage-postgres/package.json
yarn.lock

[Node-rdKafka won't handle rebalancing state](https://github.com/Blizzard/node-rdkafka/blob/master/lib/kafka-consumer.js#L49-L97) and leaves it to lib-rdkafka to do it. 
There are issues we are observing with this approach: [Link to logs where consumers are left in a Zombie state and they don't process anything even though they are connected to Kafka](https://app.datadoghq.com/logs?query=%22Broker%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AwAAAZSxarUkS2Ut_wAAABhBWlN4YXJpckFBQlNCRkpNZHJkQ1BnQ0IAAAAkMDE5NGIxODAtZGNmZS00ZWY2LTg3YWYtM2E1ZGZhM2U0YTMyAAOVbQ&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1737595743146&to_ts=1738200543146&live=true)
Other solutions rebalance on specific error codes: …

[DevX-183] Add rebalancing logic to kafka consumers

---

.changeset/sour-cougars-relax.md
packages/steveo/src/consumers/sqs.ts
packages/steveo/src/lib/manager.ts
packages/steveo/src/lib/pool.ts
packages/steveo/test/index_test.ts

This PR adds pool draining when steveo instances shutdown. 
Pools are pushed onto the global object on the NodeJs process so they can be drained when multiple steveo instances shutdown concurrently. 
Draining allows steveo instances to wait for each other resources to release before they can disconnect each other's producers.  (_Think SQS task -> publishing to Kafka or vice versa_)

[DevX-200] Drain consumer resource pools when shutting down

---

.changeset/eleven-needles-hide.md
packages/steveo/src/consumers/sqs.ts

Follow on change from:
https://github.com/ordermentum/steveo/pull/892
https://github.com/ordermentum/steveo/pull/868
This PR adds an additional check just before the SQS consumer starts processing a message to bail out if the steveo instance is supposed to shut down.
This is an edge case for applications that run multiple instances of steveo and have interdependent task (think sqs consumers publishing to kafka) and they are about to shut down.

Stop SQS consumer to process messages when shutting down

---

.changeset/icy-towns-decide.md
.changeset/tame-rings-double.md
.deepsource.toml
packages/scheduler-prisma/src/index.ts
packages/scheduler-prisma/src/utils/wait.ts
packages/scheduler-prisma/test/.eslintrc
packages/scheduler-prisma/test/fixtures/test_scheduler.fixture.ts
packages/scheduler-prisma/test/index_test.ts
packages/scheduler-prisma/test/utils/wait_test.ts
packages/scheduler-sequelize/package.json
packages/scheduler-sequelize/src/index.ts
packages/scheduler-sequelize/src/utils/wait.ts
packages/scheduler-sequelize/test/.eslintrc
packages/scheduler-sequelize/test/fixtures/test_scheduler.fixture.ts
packages/scheduler-sequelize/test/index_test.ts
packages/scheduler-sequelize/test/utils/wait_test.ts

In a recent incident we determined that pod down scaling was pulling the rug from under executing jobs causing transactions to remain locked ([slack](https://ordermentum.slack.com/archives/C08HYN9AEPQ/p1742280777879989))
----
Added a test condition to invoke the behaviour of tasks being interrupted before completing.
Added wait condition for the processing loop to terminate, [discussion here](https://ordermentum.slack.com/archives/C08HYN9AEPQ/p1742334268581819)
----
----
----

Add termination fix to sequelize terminate

---

.changeset/puny-guests-push.md
packages/cloudwatch/test/.eslintrc
packages/datadog/test/.eslintrc
packages/newrelic/test/.eslintrc
packages/sentry/test/.eslintrc
packages/statsd/test/.eslintrc
packages/steveo/src/consumers/sqs.ts
packages/steveo/test/.eslintrc
packages/steveo/test/consumer/sqs_test.ts
packages/storage-postgres/test/.eslintrc

This PR adds support for health checking FIFO sqs queues.
Also fixes eslint config across packages to refer to the right tsconfig.json file and refactors sqs consumer test file to have factory methods and use the right types.

[DevX-432] Add SQS Health check fifo compatibility
